[package]
name = "rustyfck"
version = "0.1.0"
authors = ["James Goldwater <james.goldwater@gmail.com>"]
edition= "2021"

[dependencies]
docopt = "*"
serde = "*"
lazy_static = "*"
thiserror = "*"


[profile.release]
debug = true
